### ISSUE TITLE
Could not connect device using the client uplink key

### ISSUE THREAD

**Issue by edsase** [anvil-works/anvil-pico#1]
First of all, thank you so much for this awesome library. It works well when I use the server uplink key but produces this error with the client uplink key: 
`Traceback (most recent call last):
  File "anvil/pico.py", line 154, in _connect_async
  File "anvil/pico.py", line 112, in _connect
  File "async_websocket_client.py", line 94, in handshake
OSError: [Errno 12] ENOMEM
Connecting to Anvil...
Exception in uplink reconnection loop:
`
Was the library designed to work only with the server uplink key which is indeed what is shown in the documentation example?

**Comment by patate1684** [comment]
you need to use server uplink key not client key
see here : https://anvil.works/docs/uplink/uplink_security
